testing publish stage

diff --git a/CI/Jenkinsfile b/CI/Jenkinsfile
--- a/CI/Jenkinsfile
+++ b/CI/Jenkinsfile
@@ -52,61 +52,60 @@ pipeline {
                     sh label:"Git config", script:
                     """
                         git clone 'https://${GIT_CREDS_PSW}@github.com/starknet-io/starknet-docs.git'
-                        cd starknet-docs
                         git config --global user.name "Jenkins"
                         git config --global user.email "jenkins@noreplay.com"
-                        git checkout gh-pages
                     """
-                    sh label:"Remove PR folder if exist", script:
-                    """
-                        if [ -d $PR_ID ]
-                        then
-                            rm -rf $PR_ID
-                        fi
-                    """
-                    unstash 'artifact'
-                    sh label:"Push to branch gh-pages", script:
-                    """
-                        git status
-                        git fetch
-                        git checkout gh-pages
-                        git add ${PR_ID}
+                    dir('starknet-docs') {
+                        sh label:"Remove PR folder if exist", script:
+                        """
+                            if [ -d $PR_ID ]
+                            then
+                                rm -rf $PR_ID
+                            fi
+                        """
+                        unstash 'artifact'
+                        sh label:"Push to branch gh-pages", script:
+                        """
+                            git checkout gh-pages
+                            git add ${PR_ID}
 
-                        if ! git diff-index --quiet HEAD --; then
-                            # Debug information
-                            echo "Changes detected. Committing and pushing changes."
-
-                            # Debug message
-                            echo "Commit message: ${commitMessage}"
-                        
-                            # Commit changes
-                            git commit -m "${commitMessage}"
-
-                            # Check if commit was successful
-                            if [ \$? -eq 0 ]; then
-                            # Debug information
-                            echo "Commit successful. Pushing changes."
-                        
-                            # Push changes
-                            git push
-                        
-                            # Check if push was successful
-                            if [ \$? -eq 0 ]; then
+                            if ! git diff-index --quiet HEAD --; then
                                 # Debug information
-                                echo "Push successful."
+                                echo "Changes detected. Committing and pushing changes."
+
+                                # Debug message
+                                echo "Commit message: ${commitMessage}"
+                            
+                                # Commit changes
+                                git commit -m "${commitMessage}"
+
+                                # Check if commit was successful
+                                if [ \$? -eq 0 ]; then
+                                # Debug information
+                                echo "Commit successful. Pushing changes."
+                            
+                                # Push changes
+                                git push
+                            
+                                # Check if push was successful
+                                if [ \$? -eq 0 ]; then
+                                    # Debug information
+                                    echo "Push successful."
+                                else
+                                    # Debug information
+                                    echo "Error: Push failed."
+                                fi
+                                else
+                                # Debug information
+                                echo "Error: Commit failed."
+                                fi
                             else
                                 # Debug information
-                                echo "Error: Push failed."
+                                echo "No changes found."
                             fi
-                            else
-                            # Debug information
-                            echo "Error: Commit failed."
-                            fi
-                        else
-                            # Debug information
-                            echo "No changes found."
-                        fi
-                    """
+                        """
+                    }
+                    
                 }
             }
         }
