finalize publish stage

diff --git a/CI/Jenkinsfile b/CI/Jenkinsfile
--- a/CI/Jenkinsfile
+++ b/CI/Jenkinsfile
@@ -3,7 +3,7 @@ pipeline {
     options {
        // Add timestamps to output.
        timestamps()
-       timeout(time: 45, unit: 'MINUTES')
+       timeout(time: 10, unit: 'MINUTES')
     }
     environment {
         TEST = "test"
@@ -60,6 +60,10 @@ pipeline {
                         git config --global --add safe.directory "*"
                         git config --global user.name "Jenkins Automation"
                         git config --global user.email "noreply@github.com"
+                        pwd
+                        ls -la
+                        git remote -v
+                        git status
                     """
                     sh label:"Remove PR folder if exist", script:
                     """
@@ -69,48 +73,48 @@ pipeline {
                         fi
                     """
                     unstash 'artifact'
-                    sh label:"Push to branch gh-pages", script:
-                    """
-                        git status
-                        git fetch
-                        git checkout gh-pages
-                        git add ${PR_ID}
+                    // sh label:"Push to branch gh-pages", script:
+                    // """
+                    //     git status
+                    //     git fetch
+                    //     git checkout gh-pages
+                    //     git add ${PR_ID}
 
-                        if ! git diff-index --quiet HEAD --; then
-                            # Debug information
-                            echo "Changes detected. Committing and pushing changes."
+                    //     if ! git diff-index --quiet HEAD --; then
+                    //         # Debug information
+                    //         echo "Changes detected. Committing and pushing changes."
 
-                            # Debug message
-                            echo "Commit message: ${commitMessage}"
+                    //         # Debug message
+                    //         echo "Commit message: ${commitMessage}"
                         
-                            # Commit changes
-                            git commit -m "${commitMessage}"
+                    //         # Commit changes
+                    //         git commit -m "${commitMessage}"
 
-                            # Check if commit was successful
-                            if [ \$? -eq 0 ]; then
-                            # Debug information
-                            echo "Commit successful. Pushing changes."
+                    //         # Check if commit was successful
+                    //         if [ \$? -eq 0 ]; then
+                    //         # Debug information
+                    //         echo "Commit successful. Pushing changes."
                         
-                            # Push changes
-                            git push
+                    //         # Push changes
+                    //         git push
                         
-                            # Check if push was successful
-                            if [ \$? -eq 0 ]; then
-                                # Debug information
-                                echo "Push successful."
-                            else
-                                # Debug information
-                                echo "Error: Push failed."
-                            fi
-                            else
-                            # Debug information
-                            echo "Error: Commit failed."
-                            fi
-                        else
-                            # Debug information
-                            echo "No changes found."
-                        fi
-                    """
+                    //         # Check if push was successful
+                    //         if [ \$? -eq 0 ]; then
+                    //             # Debug information
+                    //             echo "Push successful."
+                    //         else
+                    //             # Debug information
+                    //             echo "Error: Push failed."
+                    //         fi
+                    //         else
+                    //         # Debug information
+                    //         echo "Error: Commit failed."
+                    //         fi
+                    //     else
+                    //         # Debug information
+                    //         echo "No changes found."
+                    //     fi
+                    // """
                 }
             }
         }
