finalize publish stage

diff --git a/CI/Jenkinsfile b/CI/Jenkinsfile
--- a/CI/Jenkinsfile
+++ b/CI/Jenkinsfile
@@ -76,48 +76,48 @@ pipeline {
                         fi
                     """
                     unstash 'artifact'
-                    // sh label:"Push to branch gh-pages", script:
-                    // """
-                    //     git status
-                    //     git fetch
-                    //     git checkout gh-pages
-                    //     git add ${PR_ID}
+                    sh label:"Push to branch gh-pages", script:
+                    """
+                        git status
+                        git fetch
+                        git checkout gh-pages
+                        git add ${PR_ID}
 
-                    //     if ! git diff-index --quiet HEAD --; then
-                    //         # Debug information
-                    //         echo "Changes detected. Committing and pushing changes."
+                        if ! git diff-index --quiet HEAD --; then
+                            # Debug information
+                            echo "Changes detected. Committing and pushing changes."
 
-                    //         # Debug message
-                    //         echo "Commit message: ${commitMessage}"
+                            # Debug message
+                            echo "Commit message: ${commitMessage}"
                         
-                    //         # Commit changes
-                    //         git commit -m "${commitMessage}"
+                            # Commit changes
+                            git commit -m "${commitMessage}"
 
-                    //         # Check if commit was successful
-                    //         if [ \$? -eq 0 ]; then
-                    //         # Debug information
-                    //         echo "Commit successful. Pushing changes."
+                            # Check if commit was successful
+                            if [ \$? -eq 0 ]; then
+                            # Debug information
+                            echo "Commit successful. Pushing changes."
                         
-                    //         # Push changes
-                    //         git push
+                            # Push changes
+                            git push
                         
-                    //         # Check if push was successful
-                    //         if [ \$? -eq 0 ]; then
-                    //             # Debug information
-                    //             echo "Push successful."
-                    //         else
-                    //             # Debug information
-                    //             echo "Error: Push failed."
-                    //         fi
-                    //         else
-                    //         # Debug information
-                    //         echo "Error: Commit failed."
-                    //         fi
-                    //     else
-                    //         # Debug information
-                    //         echo "No changes found."
-                    //     fi
-                    // """
+                            # Check if push was successful
+                            if [ \$? -eq 0 ]; then
+                                # Debug information
+                                echo "Push successful."
+                            else
+                                # Debug information
+                                echo "Error: Push failed."
+                            fi
+                            else
+                            # Debug information
+                            echo "Error: Commit failed."
+                            fi
+                        else
+                            # Debug information
+                            echo "No changes found."
+                        fi
+                    """
                 }
             }
         }
